# Generated by Django 5.1.7 on 2025-04-06 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_live_rpg', '0002_timespent_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timespent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timespent',
            name='end_time',
            field=models.TimeField(verbose_name='Training session end'),
        ),
        migrations.AlterField(
            model_name='timespent',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timespent',
            name='start_time',
            field=models.TimeField(verbose_name='Training session start'),
        ),
    ]
